kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: online-boutique
  name: delay-150ms-20m
spec:
  selector:
    namespaces:
      - online-boutique
  mode: all
  action: delay
  duration: 20m
  delay:
    latency: 150ms
    correlation: '25'
    jitter: 50ms
  direction: both
  target:
    selector:
      namespaces:
        - online-boutique
    mode: all