kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: online-boutique
  name: full-stress-aggressive-20m
spec:
  selector:
    namespaces:
      - online-boutique
  mode: all
  stressors:
    memory:
      workers: 2
      size: 192MiB
    cpu:
      workers: 4
      load: 100
  duration: 20m